apiVersion: v1
kind: Service
metadata:
  name: auth-sidecar-demo
spec:
  type: NodePort
  selector:
    app: auth-sidecar-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    #- name: debug-bypass-auth-proxy
    #  protocol: TCP
    #  port: 9000
    #  targetPort: 9000
